#ifndef BYTECODE_VALUES_H
#define BYTECODE_VALUES_H

#define BYTECODE_PUSH 0x01
#define BYTECODE_ADD 0x02
#define BYTECODE_SUB 0x03
#define BYTECODE_MUL 0x04
#define BYTECODE_DIV 0x05
#define BYTECODE_HALT 0x06

#endif // BYTECODE_VALUES_H
