CC = emcc
CFLAGS = -Wall -Wextra -O2 -g
TARGET = bytecode_runner.js
SRCS = main.c bytecode_interpreter.c embindings.cpp

all: $(TARGET)

$(TARGET):
	$(CC) $(CFLAGS) --bind $(SRCS) -o $@ 

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean
